"""Parquet schema definitions."""
from __future__ import annotations

from typing import List, Tuple


def timeseries_columns() -> List[Tuple[str, str]]:
    """Return list of (name, dtype) for Parquet output."""
    return [
        ("run_id", "string"),
        ("seed", "int64"),
        ("slot_idx", "int64"),
        ("time_s", "float64"),
        ("x", "float64"),
        ("y", "float64"),
        ("z", "float64"),
        ("vx", "float64"),
        ("vy", "float64"),
        ("vz", "float64"),
        ("battery_wh", "float64"),
        ("target_idx", "int64"),
        ("target_x", "float64"),
        ("target_y", "float64"),
        ("target_z", "float64"),
        ("md_target_x", "float64"),
        ("md_target_y", "float64"),
        ("md_target_z", "float64"),
        ("md_service_x", "float64"),
        ("md_service_y", "float64"),
        ("md_service_z", "float64"),
        ("roll", "float64"),
        ("pitch", "float64"),
        ("yaw", "float64"),
        ("omega_x", "float64"),
        ("omega_y", "float64"),
        ("omega_z", "float64"),
        ("dyn_mode", "string"),
        ("rotor_omega_1", "float64"),
        ("rotor_omega_2", "float64"),
        ("rotor_omega_3", "float64"),
        ("rotor_omega_4", "float64"),
        ("thrust", "float64"),
        ("tau_x", "float64"),
        ("tau_y", "float64"),
        ("tau_z", "float64"),
        ("wind_x", "float64"),
        ("wind_y", "float64"),
        ("wind_z", "float64"),
        ("wind_speed", "float64"),
        ("pos_error", "float64"),
        ("pos_error_md", "float64"),
        ("pos_error_md_service", "float64"),
        ("E_total", "float64"),
        ("E_mov", "float64"),
        ("E_tr", "float64"),
        ("E_comp", "float64"),
        ("D_total", "float64"),
        ("D_tr", "float64"),
        ("D_comp", "float64"),
        ("D_q", "float64"),
        ("D_uavq", "float64"),
        ("S", "float64"),
        ("viol_speed", "int8"),
        ("viol_alt", "int8"),
        ("viol_battery", "int8"),
        ("viol_obstacle", "int8"),
        ("viol_att", "int8"),
        ("viol_angrate", "int8"),
        ("viol_rotor", "int8"),
        ("reroute", "int8"),
    ]
